# This is the main configuration file for the Petaly tool.
# It includes the workspace_config and global_settings sections.
[workspace_config]

# The following parameter specifies the absolute path to the pipeline directory.
# All pipelines created by init are persisted in this directory.
pipeline_dir_path=

# The following parameter specifies the absolute path to the log directory.
logs_dir_path=

# The following parameter specifies the absolute path to the output directory.
# Data output directory is temporary directory used as transition space between source and destination.
output_dir_path=

[global_settings]
# The logging mode has two settings: INFO and DEBUG.
# By default, it is set to INFO, which generates minimal log output.
# If an issue occurs, switch to DEBUG for more detailed output that can assist in troubleshooting.
logging_mode=INFO

# Run Petaly in one of the following APP modes:
# CLI - [default] command-line in your local or server environment
# AGENT - via AI agent (EXPERIMENTAL)
app_mode=CLI

# In case app_mode=AGENT
[ai_settings]
# This is main AI settings section
# Select the LLM provider to use openai or anthropic. (default: openai)
llm_provider=openai

# Select the LLM model to use. 
# Tested with gpt-4 (openai), claude-3-opus-20240229 (anthropic)
llm_model=gpt-4

# Path to the memory file. Default is ~/.petaly/agent_memory.json
agent_memory_file=~/.petaly/agent_memory.json

# Provide AI_AGENT_API_KEY as an environment variable: export AI_AGENT_API_KEY="YOUR-AI-AGENT-API-KEY-OR-TOKEN"
# Alternative and for the test purpose you can set it directly here
ai_agent_api_key=